export * from './delivery-route.model';
export * from './delivery-route-popup.service';
export * from './delivery-route.service';
export * from './delivery-route-dialog.component';
export * from './delivery-route-delete-dialog.component';
export * from './delivery-route-detail.component';
export * from './delivery-route.component';
export * from './managment-routes.component';
export * from './delivery-route.route';
